config/routes.rb
Rails.application.routes.draw do
  # Clearance
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]
  resources :users, only: %i[new create] do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
  end

  resource :user, only: %i[edit update]

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'

  resources :timer, only: :index
  resources :reports, only: :index
  resources :clients, only: %i[create update destroy]
  resources :projects do
    resources :tasks, only: %i[new edit create update destroy] do
      post :toggle, on: :member
    end
  end
  resources :slots, only: %i[edit show create update destroy] do
    post :stop, on: :member
  end
  resources :manual_slots, only: %i[new create]

  root 'timer#index'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  COLORS = ['#1abc9c', '#2ecc71', '#3498db', '#9b59b6', '#16a085', '#27ae60', '#2980b9', '#8e44ad', '#f1c40f',
            '#e67e22', '#e74c3c', '#f39c12', '#d35400', '#c0392b'].freeze

  CURRENCIES = %w[USD GBP EUR AUD CAD].freeze

  has_many :tasks, dependent: :destroy
  belongs_to :user

  validates :name, presence: true

  monetize :rate_cents, as: :rate, allow_nil: true

  scope :enabled, -> { where(disabled_at: nil) }

  def disabled
    disabled_at?
  end

  def disabled=(value)
    self.disabled_at = (value == '1' ? Time.current : nil)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_tab

  def index
    @projects = project_scope.order(:name)
  end

  def show
  end

  def new
    @project = project_scope.new
  end

  def create
    @project = project_scope.build(project_params)
    if @project.save
      redirect_to @project, notice: 'Great! Another project in the bag.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Well done updating that project, it was about time!'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'You deleted it! Probably it deserved it.'
  end

  private

  def set_project
    @project = project_scope.find(params[:id])
  end

  def project_scope
    current_user.projects
  end

  def project_params
    params.require(:project).permit(:name, :color, :rate_cents, :rate_currency, :disabled)
  end

  def set_tab
    activate_tab :projects
  end
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= bootstrap_form_for project do |form| %>
      <%= form.text_field :name %>

      <div class="row">
        <div class="col-md-5">
          <%= form.number_field :rate_cents, label: 'Rate per hour (in cents)' %>
        </div>
        <div class="col-md-4">
          <%= form.select :rate_currency, Project::CURRENCIES.collect { |c| [c, c] }, { label: 'Currency' }, class: 'w-auto' %>
        </div>
      </div>

      <div class="form-colors">
        <% Project::COLORS.each do |color| %>
          <%= form.radio_button_without_bootstrap :color, color %>
          <label for="project_color_<%= color.sub('#', '') %>" style="background:<%= color %>;"></label>
        <% end %>
      </div>

      <%= form.check_box :disabled %>

      <div class="mt-4">
        <%= form.submit 'Save', class: 'btn btn-sm btn-secondary mr-1' %>
        <%= link_to 'Cancel', (form.object.persisted? ? form.object : projects_path), class: 'text-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1 class="h3 mb-5">Editing Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="row mb-5">
  <div class="col-md-6">
    <h1 class="h3">Projects</h1>
  </div>
  <div class="col-md-6 text-right">
    <%= link_to new_project_path, data: { toggle: 'tooltip' }, title: 'Add new project', class: 'btn btn-round btn-outline-secondary text-muted text-sm' do %>
      <i class="iconly-0823-plus"></i>
    <% end %>
  </div>
</div>

<% if @projects.present? %>
  <% @projects.each do |project| %>
    <div class="item-brd">
      <span class="proj-col-label-sm mr-1" style="background:<%= project.color %>"></span>
      <%= link_to project.name, project, class: 'text-dark' %>
      <% if project.disabled %>
        <span class="badge badge-light">Disabled</span>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p class="text-muted">
    You don't have any projects yet.
    <%= link_to 'Create one now', new_project_path %>.
  </p>
<% end %>

app/views/projects/new.html.erb
<h1 class="h3 mb-5">New Project</h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<div class="row mb-1">
  <div class="col-md-9">
    <h1 class="h3">
      <span class="proj-col-label mr-1" style="background:<%= @project.color %>"></span>
      <%= @project.name %>
    </h1>
  </div>
  <div class="col-md-3 text-right">
    <%= link_to @project, method: :delete, data: { confirm: 'Are you sure you want to delete this project?', toggle: 'tooltip' }, title: 'Delete project', class: 'btn btn-round btn-outline-secondary text-sm' do %>
      <i class="iconly-0129-trash"></i>
    <% end %>
    <%= link_to [:edit, @project], data: { toggle: 'tooltip' }, title: 'Edit project', class: 'btn btn-round btn-outline-secondary text-sm' do %>
      <i class="iconly-0014-pencil"></i>
    <% end %>
    <%= link_to [:new, @project, :task], remote: true, data: { toggle: 'tooltip', replace: '#project-task-' }, title: 'Add new task', class: 'btn btn-round btn-outline-secondary text-sm ml-3' do %>
      <i class="iconly-0823-plus"></i>
    <% end %>
  </div>
</div>

<div class="text-muted mb-4">
  <% if @project.disabled %>
    <span class="badge badge-warning mr-1">Disabled</span>
  <% end %>
  <% if @project.rate.present? %>
    Rate: <%= humanized_money_with_symbol @project.rate %> per hour
  <% end %>
</div>

<div class="item-brd" id="project-task-"></div>

<div id="project-tasks">
  <%= render @project.tasks.order(:name) %>
</div>