config/routes.rb
Rails.application.routes.draw do
  # Clearance
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]
  resources :users, only: %i[new create] do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
  end

  resource :user, only: %i[edit update]

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'

  resources :timer, only: :index
  resources :reports, only: :index
  resources :clients, only: %i[create update destroy]
  resources :projects do
    resources :tasks, only: %i[new edit create update destroy] do
      post :toggle, on: :member
    end
  end
  resources :slots, only: %i[edit show create update destroy] do
    post :stop, on: :member
  end
  resources :manual_slots, only: %i[new create]

  root 'timer#index'
end

app/controllers/manual_slots_controller.rb
# frozen_string_literal: true

class ManualSlotsController < ApplicationController
  before_action :set_tab

  def new
    @slot = Slot.new
  end

  def create
    @slot = current_user.slots.build(slot_params)
    @slot.creating_manually = true
    if @slot.save
      redirect_to timer_index_path, notice: '<i class="iconly-0651-smile"></i> Got it! New time worked created.'
    else
      render :new
    end
  end

  private

  def set_tab
    activate_tab :manual
  end

  def slot_params
    params.require(:slot).permit(:task_id, :start_at_formatted, :end_at_time)
  end
end

app/views/manual_slots/new.html.erb
<h1 class="h3 mb-5">What did you work on?</h1>

<div class="row">
  <div class="col-md-6">
    <%= bootstrap_form_for @slot, url: manual_slots_path do |form| %>
      <%= form.select :task_id, grouped_tasks_options(@slot) %>
      <%= form.text_field :start_at_formatted, label: 'Started on', class: 'w-auto' %>
      <%= form.time_field :end_at_time, label: 'Ended on', class: 'w-auto', placeholder: '00:00' %>
      <%= form.submit 'Save', class: 'btn btn-sm btn-success' %>
    <% end %>
  </div>
</div>


<script>
  $('#slot_start_at_formatted').daterangepicker({
    singleDatePicker: true,
    timePicker: true,
    timePicker24Hour: true,
    locale: {
      format: 'DD/MM/YYYY HH:MM',
      firstDay: 1
    }
  });
</script>