config/routes.rb
Rails.application.routes.draw do
  # Clearance
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]
  resources :users, only: %i[new create] do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
  end

  resource :user, only: %i[edit update]

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'

  resources :timer, only: :index
  resources :reports, only: :index
  resources :clients, only: %i[create update destroy]
  resources :projects do
    resources :tasks, only: %i[new edit create update destroy] do
      post :toggle, on: :member
    end
  end
  resources :slots, only: %i[edit show create update destroy] do
    post :stop, on: :member
  end
  resources :manual_slots, only: %i[new create]

  root 'timer#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  before_action :require_login, :set_user_time_zone, :load_current_slot

  helper_method :active_tab, :current_slot

  private

  attr_reader :active_tab, :current_slot

  def load_current_slot
    return unless signed_in?
    @current_slot = current_user.slots.pending.last
  end

  def load_recent_slots
    @recent_slots = current_user.slots.ended.recent
                                .includes(task: :project).to_a
                                .group_by { |s| s.start_at_dt.to_date }
  end

  def set_user_time_zone
    Time.zone = current_user.time_zone if signed_in?
  end

  def activate_tab(tab)
    @active_tab = tab
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nav_link(name, path, tab, icon)
    class_name = %i[nav-link]
    class_name << (active_tab == tab ? 'text-pink' : 'text-muted')
    link_to path, class: class_name.join(' ') do
      content_tag(:i, '', class: "#{icon} mr-2") + name
    end
  end

  def current_user_tasks
    current_user.tasks
                .in_progress
                .includes(:project)
                .joins(:project)
                .merge(Project.enabled)
                .order('projects.name')
                .group_by(&:project)
  end
end

app/views/application/_footer.html.erb
<footer class="app-footer mt-5">
  <div class="container py-3 text-center">
    <span class="text-bolder text-pale">tracker</span>
  </div>
</footer>

app/views/application/_header.html.erb
  <nav class="navbar fixed-top navbar-expand-md navbar-light app-header pg-sign-<%= signed_in? %>" id="app-header" data-turbolinks-permanent>
    <%= link_to '/', class: 'navbar-brand text-bold' do %>
      <span>
        <i class="iconly-0750-alarm-check"></i>
      </span>
      tracker
    <% end %>

    <% if signed_in? %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mr-1">
          <%= link_to '#start', class: 'nav-link text-lg', data: { target: 'timer.playNow', action: 'timer#toggle' } do %>
            <i class="iconly-0875-play-circle"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <span class="navbar-text app-timer-ticker" data-target="timer.ticker">00:00:00</span>
        </li>
        <li class="nav-item dropdown app-timer-tasks">
          <a class="nav-link text-truncate task-name <%= 'loaded' if current_slot.present? %>" data-target="timer.taskNameLink" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="iconly-0827-chevron-down text-xs"></i>
            <span data-target="timer.taskName">
              <% if current_slot.present? %>
                <%= render('task_name', task: current_slot.task) %>
              <% else %>
                What are you working on ?
              <% end %>
            </span>
          </a>
          <div class="dropdown-menu dropdown-menu-lg" aria-labelledby="app-header-drop-tasks">
            <% current_user_tasks.each do |project, tasks| %>
              <h6 class="dropdown-header text-sm pl-2">
                <span class="proj-col-label-sm mr-1" style="background:<%= project.color %>"></span>
                <%= project.name %>
              </h6>
              <% tasks.each do |task| %>
                <%= link_to '#start', class: 'dropdown-item', data: {
                    target: 'task',
                    action: 'timer#playTask',
                    name:   render(partial: 'task_name', locals: { task: task }),
                    url:    slots_path(slot: { task_id: task.id }) } do %>
                  <%= task.name %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </li>
      </ul>
    <% end %>

    <ul class="navbar-nav ml-auto">
      <% if signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="app-header-user-drop-label" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="iconly-0287-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="app-header-user-drop-label">
            <%= link_to 'Settings', edit_user_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Sign out', sign_out_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item mt-1">
          <%= link_to 'Sign in', sign_in_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', sign_up_path, class: 'btn btn-sm btn-success mt-1' %>
        </li>
      <% end %>
    </ul>
  </nav>

app/views/application/_nav.html.erb
<ul class="nav flex-column mt-md-2">
  <li class="nav-item">
    <%= nav_link 'Timer', timer_index_path, :timer, 'iconly-0741-history2' %>
  </li>
  <li class="nav-item">
    <%= nav_link 'Add slot', new_manual_slot_path, :manual, 'iconly-0823-plus' %>
  </li>
  <li class="nav-item">
    <%= nav_link 'Reports', reports_path, :reports, 'iconly-0506-pie-chart2' %>
  </li>
  <li class="nav-item">
    <%= nav_link 'Projects', projects_path, :projects, 'iconly-0277-book2' %>
  </li>
</ul>

app/views/application/_task_name.html.erb
<%= task.name %>
<div class="text-xs text-muted">
  <span class="proj-col-label-sm mr-1" style="background:<%= task.project.color %>"></span>
  <%= task.project.name %>
</div>