config/routes.rb
Rails.application.routes.draw do
  # Clearance
  resources :passwords, controller: 'clearance/passwords', only: [:create, :new]
  resource :session, controller: 'clearance/sessions', only: [:create]
  resources :users, only: %i[new create] do
    resource :password, controller: 'clearance/passwords', only: [:create, :edit, :update]
  end

  resource :user, only: %i[edit update]

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'users#new', as: 'sign_up'

  resources :timer, only: :index
  resources :reports, only: :index
  resources :clients, only: %i[create update destroy]
  resources :projects do
    resources :tasks, only: %i[new edit create update destroy] do
      post :toggle, on: :member
    end
  end
  resources :slots, only: %i[edit show create update destroy] do
    post :stop, on: :member
  end
  resources :manual_slots, only: %i[new create]

  root 'timer#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-content <%= 'disabled' if current_slot.blank? %>" data-controller="timer"
        data-timer-url="<%= slots_path %>"
        data-timer-start="<%= current_slot.try(:start_at) %>"
        data-timer-stop="<%= current_slot.present? ? stop_slot_path(current_slot) : '' %>">
      <%= render 'header' %>
      <div class="container">
        <% if signed_in? %>
          <div class="row">
            <div class="col-md-2">
              <%= render 'nav' %>
            </div>
            <div class="col-md-10">
              <%= render_flash %>
              <%= yield %>
            </div>
          </div>
        <% else %>
          <%= render_flash %>
          <%= yield %>
        <% end %>
      </div>
    </div>
    <%= render 'footer' %>
  </body>
</html>